import type { Metadata } from "next";
import "./globals.css";
import { ReduxProvider } from "@/redux/ReduxProvider";
import { Inter } from "next/font/google";
import { SessionValidator } from "@/lib/auth/session-validator";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await SessionValidator();

  return (
    <html lang="en" className={inter.className} suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  let storagedTheme = localStorage.getItem("theme-tracker");
                  if (storagedTheme === "system"){ storagedTheme = null};
                  const preferTheme = window.matchMedia("(prefers-color-scheme: dark)").matches;
                  const theme = (storagedTheme )|| (preferTheme ? "dark" : "light");
                        
                  document.documentElement.classList.toggle("dark", theme === "dark");
                  document.documentElement.classList.toggle("light", theme === "light");
                        
                } catch (_) {}
              }
              )();`,
          }}
        />
      </head>
      <body className={`antialiased`}>
        <ReduxProvider session={session}>{children}</ReduxProvider>
      </body>
    </html>
  );
}
