name: CI

on:
  push:
    branches:
      - feature/docker-aws

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/testdb
      DIRECT_URL: postgresql://postgres:postgres@postgres:5432/testdb
      NEWS_API_KEY: test
      ACCESS_SECRET: test
      REFRESH_SECRET: test
      ACCESS_TOKEN_EXPIRES: 15m
      REFRESH_TOKEN_EXPIRES: 7d
      RESEND_API_KEY: test
      APP_URL: http://localhost:3000

    services:
      postgres:
        image: postgres:17

        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb

        ports:
          - 5432:5432

        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.jobs
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build aplication
        run: npm run build

      - name: Build docker image
        run: docker build -t crypto-tracker .

      - name: Run migrations
        run: npx prisma migrate deploy
